# Generated by Django 4.0.7 on 2023-02-20 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True)),
                ('query_timestamp', models.DateTimeField(null=True)),
                ('response', models.TextField(blank=True)),
                ('response_timestamp', models.DateTimeField(null=True)),
                ('final_language', models.CharField(max_length=10, null=True)),
                ('language_confidence', models.FloatField(blank=True, null=True)),
                ('created', models.IntegerField(null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
