# Generated by Django 4.0.7 on 2023-02-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='translated_query',
            field=models.TextField(blank=True),
        ),
    ]
